// paises.js
const paises = [
  { nome: "Afeganistão", sigla: "AFG" },
  { nome: "África do Sul", sigla: "ZAF" },
  { nome: "Albânia", sigla: "ALB" },
  { nome: "Alemanha", sigla: "DEU" },
  { nome: "Andorra", sigla: "AND" },
  { nome: "Angola", sigla: "AGO" },
  { nome: "Antígua e Barbuda", sigla: "ATG" },
  { nome: "Arábia Saudita", sigla: "SAU" },
  { nome: "Argélia", sigla: "DZA" },
  { nome: "Argentina", sigla: "ARG" },
  { nome: "Armênia", sigla: "ARM" },
  { nome: "Austrália", sigla: "AUS" },
  { nome: "Áustria", sigla: "AUT" },
  { nome: "Azerbaijão", sigla: "AZE" },

  { nome: "Bahamas", sigla: "BHS" },
  { nome: "Bangladesh", sigla: "BGD" },
  { nome: "Barbados", sigla: "BRB" },
  { nome: "Bélgica", sigla: "BEL" },
  { nome: "Belize", sigla: "BLZ" },
  { nome: "Benim", sigla: "BEN" },
  { nome: "Bolívia", sigla: "BOL" },
  { nome: "Bósnia e Herzegovina", sigla: "BIH" },
  { nome: "Botsuana", sigla: "BWA" },
  { nome: "Brasil", sigla: "BRA" },
  { nome: "Brunei", sigla: "BRN" },
  { nome: "Bulgária", sigla: "BGR" },
  { nome: "Burkina Faso", sigla: "BFA" },
  { nome: "Burundi", sigla: "BDI" },

  { nome: "Cabo Verde", sigla: "CPV" },
  { nome: "Camarões", sigla: "CMR" },
  { nome: "Canadá", sigla: "CAN" },
  { nome: "Catar", sigla: "QAT" },
  { nome: "Cazaquistão", sigla: "KAZ" },
  { nome: "Chade", sigla: "TCD" },
  { nome: "Chile", sigla: "CHL" },
  { nome: "China", sigla: "CHN" },
  { nome: "Chipre", sigla: "CYP" },
  { nome: "Colômbia", sigla: "COL" },
  { nome: "Comores", sigla: "COM" },
  { nome: "Congo", sigla: "COG" },
  { nome: "Coreia do Norte", sigla: "PRK" },
  { nome: "Coreia do Sul", sigla: "KOR" },
  { nome: "Costa do Marfim", sigla: "CIV" },
  { nome: "Costa Rica", sigla: "CRI" },
  { nome: "Croácia", sigla: "HRV" },
  { nome: "Cuba", sigla: "CUB" },

  { nome: "Dinamarca", sigla: "DNK" },
  { nome: "Djibuti", sigla: "DJI" },
  { nome: "Dominica", sigla: "DMA" },

  { nome: "Egito", sigla: "EGY" },
  { nome: "El Salvador", sigla: "SLV" },
  { nome: "Emirados Árabes Unidos", sigla: "ARE" },
  { nome: "Equador", sigla: "ECU" },
  { nome: "Eritreia", sigla: "ERI" },
  { nome: "Eslováquia", sigla: "SVK" },
  { nome: "Eslovênia", sigla: "SVN" },
  { nome: "Espanha", sigla: "ESP" },
  { nome: "Estados Unidos", sigla: "USA" },
  { nome: "Estônia", sigla: "EST" },
  { nome: "Etiópia", sigla: "ETH" },

  { nome: "Fiji", sigla: "FJI" },
  { nome: "Filipinas", sigla: "PHL" },
  { nome: "Finlândia", sigla: "FIN" },
  { nome: "França", sigla: "FRA" },

  { nome: "Gabão", sigla: "GAB" },
  { nome: "Gâmbia", sigla: "GMB" },
  { nome: "Gana", sigla: "GHA" },
  { nome: "Geórgia", sigla: "GEO" },
  { nome: "Grécia", sigla: "GRC" },
  { nome: "Guatemala", sigla: "GTM" },

  { nome: "Haiti", sigla: "HTI" },
  { nome: "Honduras", sigla: "HND" },
  { nome: "Hungria", sigla: "HUN" },

  { nome: "Índia", sigla: "IND" },
  { nome: "Indonésia", sigla: "IDN" },
  { nome: "Irã", sigla: "IRN" },
  { nome: "Iraque", sigla: "IRQ" },
  { nome: "Irlanda", sigla: "IRL" },
  { nome: "Islândia", sigla: "ISL" },
  { nome: "Israel", sigla: "ISR" },
  { nome: "Itália", sigla: "ITA" },

  { nome: "Jamaica", sigla: "JAM" },
  { nome: "Japão", sigla: "JPN" },
  { nome: "Jordânia", sigla: "JOR" },

  { nome: "Quênia", sigla: "KEN" },
  { nome: "Kuwait", sigla: "KWT" },

  { nome: "Laos", sigla: "LAO" },
  { nome: "Letônia", sigla: "LVA" },
  { nome: "Líbano", sigla: "LBN" },
  { nome: "Libéria", sigla: "LBR" },
  { nome: "Líbia", sigla: "LBY" },
  { nome: "Lituânia", sigla: "LTU" },
  { nome: "Luxemburgo", sigla: "LUX" },

  { nome: "Madagascar", sigla: "MDG" },
  { nome: "Malásia", sigla: "MYS" },
  { nome: "Malawi", sigla: "MWI" },
  { nome: "Maldivas", sigla: "MDV" },
  { nome: "Mali", sigla: "MLI" },
  { nome: "Malta", sigla: "MLT" },
  { nome: "Marrocos", sigla: "MAR" },
  { nome: "México", sigla: "MEX" },
  { nome: "Moçambique", sigla: "MOZ" },

  { nome: "Namíbia", sigla: "NAM" },
  { nome: "Nepal", sigla: "NPL" },
  { nome: "Nicarágua", sigla: "NIC" },
  { nome: "Níger", sigla: "NER" },
  { nome: "Nigéria", sigla: "NGA" },
  { nome: "Noruega", sigla: "NOR" },

  { nome: "Nova Zelândia", sigla: "NZL" },

  { nome: "Omã", sigla: "OMN" },

  { nome: "Países Baixos - Holanda", sigla: "NLD" },
  { nome: "Panamá", sigla: "PAN" },
  { nome: "Paraguai", sigla: "PRY" },
  { nome: "Peru", sigla: "PER" },
  { nome: "Polônia", sigla: "POL" },
  { nome: "Portugal", sigla: "PRT" },

  { nome: "Reino Unido", sigla: "GBR" },
  { nome: "República Dominicana", sigla: "DOM" },
  { nome: "Romênia", sigla: "ROU" },
  { nome: "Ruanda", sigla: "RWA" },

  { nome: "Senegal", sigla: "SEN" },
  { nome: "Sérvia", sigla: "SRB" },
  { nome: "Singapura", sigla: "SGP" },
  { nome: "Síria", sigla: "SYR" },
  { nome: "Somália", sigla: "SOM" },
  { nome: "Sri Lanka", sigla: "LKA" },
  { nome: "Suécia", sigla: "SWE" },
  { nome: "Suíça", sigla: "CHE" },

  { nome: "Tailândia", sigla: "THA" },
  { nome: "Tanzânia", sigla: "TZA" },
  { nome: "Tunísia", sigla: "TUN" },
  { nome: "Turquia", sigla: "TUR" },

  { nome: "Ucrânia", sigla: "UKR" },
  { nome: "Uganda", sigla: "UGA" },
  { nome: "Uruguai", sigla: "URY" },

  { nome: "Venezuela", sigla: "VEN" },
  { nome: "Vietnã", sigla: "VNM" },

  { nome: "Zâmbia", sigla: "ZMB" },
  { nome: "Zimbábue", sigla: "ZWE" }
];